### PR TITLE
Upgraded Cake to 0.17.0

### PR DESCRIPTION
**Pull request by devlead**
* also changed Cake to build dependency.

### CODE REVIEW

**Comment by donnib** [comment]
@reicheltp Hey it would be cool if you could approve this so we have still use use HockeyApp with Cake's new 0.18 version.

**Comment by donnib** [comment]
@reicheltp u there ?

**Comment by Cheesebaron** [comment]
Would be really great if we could get this PR merged and released. As it is now this AddIn does not work with Cake 0.18.0

**Comment by gep13** [comment]
@reicheltp if you are not in a position to do this work, are you ok with us (the Cake Team) doing the work on your behalf?  Thanks!

**Comment by reicheltp** [comment]
@donnib @Cheesebaron  I'm really sorry; illness and lots of work currently blocking me getting this done. The CI is not fully setup so just merge did not automatically release this.

@gep13 That would be awesome!

**Comment by gep13** [comment]
>@reicheltp said...
That would be awesome!

Ok, let me see what I can do.

@reicheltp Hope you are feeling better.

**Comment by Cheesebaron** [comment]
Still would love this to get merged and released. 

❤️
Tomasz

**Comment by gep13** [comment]
@Cheesebaron yip, it hasn't been forgotten about, just on a list.

**Comment by Cheesebaron** [comment]
@gep13 any news here? Do you need help?

**Comment by gep13** [comment]
@devlead I am going to go ahead and close this.  The Cake.Core dependency on the develop branch of this repository has already been updated to the minimum required version of 0.16.2 in order for it to work with the latest version of Cake.  This work was done as part of the migration to using the VS 2017 Tooling, and as such, the work in this PR could not be included.

@Cheesebaron Version 0.3.0-unstable0030 has just been pushed here:

https://myget.org/feed/cake-contrib/package/nuget/Cake.HockeyApp

Would you be in position to take this for a spin before rolling it out to NuGet.org?  Thanks!

**Pull request closed without merging**
